name: Scrape Latest Anime Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Langkah ini tidak lagi diperlukan karena skrip tes membuat folder sendiri
      # - name: Create details directory
      #   run: mkdir -p details

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright browsers
        run: python -m playwright install chromium --with-deps

      # ==================================================
      # === PERUBAHAN DI SINI ===
      - name: Run scraper TEST
        run: python test_scrape.py
      # ==================================================

      # Kita matikan dulu langkah commit agar tidak error jika tesnya ingin diubah-ubah
      # - name: Commit and push if content changed
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: 'Update anime data'
      #     file_pattern: 'homepage.json details/*.json'
      #     commit_options: '--allow-empty'
