# Nama workflow
name: Scrape Latest Anime Data

# Pemicu: Hanya berjalan jika dipicu manual dari tab Actions
on:
  workflow_dispatch:

# Izin yang dibutuhkan untuk commit dan push
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengunduh kode dari repositori
      - name: Check out repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Langkah 3: Menginstal semua library Python yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah 4: Menginstal browser untuk Playwright
      - name: Install Playwright browsers
        run: python -m playwright install chromium --with-deps

      # Langkah 5: Menjalankan skrip tes. 
      # ID 'test_step' diberikan agar kita bisa memeriksa hasilnya.
      # `continue-on-error: true` agar langkah selanjutnya tetap berjalan.
      - name: Run scraper TEST with screenshot
        id: test_step
        run: python test_scrape.py
        continue-on-error: true

      # Langkah 6: Commit dan push file JSON HANYA JIKA TES BERHASIL
      # `if: steps.test_step.outcome == 'success'` memastikan langkah ini hanya berjalan jika tes tidak gagal.
      - name: Commit and push TEST results
        if: steps.test_step.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Add test scrape results'
          file_pattern: 'details_test/*.json'
      
      # Langkah 7: Mengunggah screenshot HANYA JIKA TES GAGAL
      # `if: steps.test_step.outcome == 'failure'` memastikan langkah ini hanya berjalan jika tes gagal.
      - name: Upload Debug Screenshot on Failure
        if: steps.test_step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug_screenshot.png
