# Nama workflow yang akan muncul di tab Actions di GitHub
name: Scrape Latest Anime Updates

# Pemicu (trigger) untuk menjalankan workflow ini
on:
  # Menjalankan secara otomatis sesuai jadwal (cron job)
  schedule:
    # Cron syntax: menit jam hari(bulan) bulan hari(minggu)
    # '0 */6 * * *' berarti berjalan setiap 6 jam.
    # Contoh lain: '0 0 * * *' berarti setiap hari jam 00:00 UTC.
    - cron: '0 */6 * * *'
  
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Mendefinisikan pekerjaan (jobs) yang akan dijalankan
jobs:
  scrape:
    # Menentukan mesin virtual yang akan digunakan
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dieksekusi
    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda ke mesin virtual
      - name: Check out repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Anda bisa ganti versi Python jika perlu

      # Langkah 3: Menginstal library yang dibutuhkan dari requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah 4: Menjalankan skrip Python untuk scraping
      - name: Run scraper
        run: python scrape.py # Pastikan nama file ini sesuai dengan skrip Anda

      # Langkah 5: Melakukan commit dan push file JSON yang dihasilkan ke repositori
      - name: Commit and push if content changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Pesan commit yang akan digunakan
          commit_message: 'Update latest anime data'
          # Pola file yang akan di-commit. Hanya commit jika file ini berubah.
          file_pattern: 'latest_updates.json'
