name: Scrape Latest Anime Updates

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah tambahan: Menginstal browser yang dibutuhkan Playwright
      - name: Install Playwright browsers
        run: python -m playwright install chromium --with-deps

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push if content changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update latest anime data'
          file_pattern: 'latest_updates.json'
