# Nama workflow yang akan muncul di tab Actions di GitHub
name: Scrape Latest Anime Updates

# Pemicu (trigger) untuk menjalankan workflow ini
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# **TAMBAHAN PENTING: Memberikan izin tulis ke workflow**
permissions:
  contents: write

# Mendefinisikan pekerjaan (jobs) yang akan dijalankan
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper
        run: python scrape.py

      # Langkah ini sekarang akan berhasil karena sudah memiliki izin
      - name: Commit and push if content changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update latest anime data'
          file_pattern: 'latest_updates.json'
